### ISSUE TITLE
ats_slice_range   编译问题

### ISSUE THREAD

**Issue by GarfieldLinux** [oxwangfeng/ats_slice_range#1]
Hey  ：
   最近在看你的插件   你的插件是不是代码上有点问题 
1. 447 行  是不是不小心多了字符 ATS_UNUSED 
2. 头文件 ts/ink_defs.h  not found  我删掉了 也编译通过了 

能否确认上面2个问题  存在的话 编译不通过  我用的ATS 版本不是最新的  比较旧   。 

  Thanks 。

**Comment by oxwangfeng** [comment]
ATS_UNUSED表示这个字段没有使用，不过不能去掉啊，因为range_transform是个TSTransformCreate的回调函数，必须有三个入参，这个是固定的；（具体你可以参考trafficserver上的插件代码）
ts/ink_defs.h不存在，估计低版本没有这个文件；4.2以上都需要这个文件；

我用的是ats 4.2.2版本。4.2.2版本是不能删除这两行的；
低版本的ats，你可以适当调整代码。
